version: '3'
networks:
  microservices:
    driver: bridge

services:
  serviceregistry:
    image: 'naveenkerla/serviceregistry:latest'
    container_name: serviceregistry
    ports:
      - '8761:8761'
    extends:
      file: common-config.yaml
      service: network-deploy-service

  configserver:
    image: 'naveenkerla/configserver:0.0.1'
    container_name: configserver
    ports:
      - '9296:9296'
    extends:
      file: common-config.yaml
      service: network-deploy-service
    environment:
      EUREKA_SERVER_ADDRESS: "http://serviceregistry:8761/eureka"
    healthcheck:
      test: ["CMD","curl","-f", "http://configserver:9296/actuator/health"]
      retries: 5
      timeout: 5s
      interval: 10s
    depends_on:
      - serviceregistry

  orderservice:
    image: 'naveenkerla/orderservice'
    container_name: orderservice
    ports:
      - '8082:8082'
    extends:
      file: common-config.yaml
      service: business-services-base-config
    depends_on:
      configserver:
        condition: service_healthy

  cloudgateway:
    image: 'naveenkerla/cloudgateway:0.0.1'
    container_name: cloudgateway
    ports:
      - '9090:9090'
    extends:
      file: common-config.yaml
      service: business-services-base-config
    depends_on:
      configserver:
        condition: service_healthy