version: '3.8'
networks:
  microservices:
    driver: bridge

services:
  serviceregistry:
    image: 'naveenkerla/serviceregistry'
    container_name: serviceregistry
    ports:
      - '8761:8761'
    extends:
      file: common-config.yaml
      service: network-deploy-service

#  rabbit:
#    image: 'rabbitmq:4-management'
#    hostname: rabbitmq
#    ports:
#      - "5672:5672" # AMQP protocol (used by Spring Boot)
#      - "15672:15672" # RabbitMQ management UI
#    healthcheck:
#      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 10s
#    extends:
#      file: common-config.yaml
#      service: network-deploy-service

  configserver:
    image: 'naveenkerla/configserver'
    container_name: configserver
    ports:
      - '9296:9296'
    extends:
      file: common-config.yaml
      service: network-deploy-service
    environment:
      EUREKA_SERVER_ADDRESS: "http://serviceregistry:8761/eureka"
    healthcheck:
      test: ["CMD","curl","-f", "http://configserver:9296/actuator/health"]
      retries: 5
      timeout: 5s
      interval: 10s
      start_period: 10s
#    depends_on:
#      rabbit:
#        condition: service_healthy

  orderservice:
    image: 'naveenkerla/orderservice'
    container_name: orderservice
    ports:
      - '8082:8082'
    extends:
      file: common-config.yaml
      service: business-services-base-config
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/order_db
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      configserver:
        condition: service_healthy
      mysql:
        condition: service_healthy

  productservice:
    image: 'naveenkerla/productservice'
    container_name: productservice
    ports:
      - '8080:8080'
    extends:
      file: common-config.yaml
      service: business-services-base-config
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/product_db
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      configserver:
        condition: service_healthy
      mysql:
        condition: service_healthy

  paymentservice:
    image: 'naveenkerla/paymentservice'
    container_name: paymentservice
    ports:
      - '8081:8081'
    extends:
      file: common-config.yaml
      service: business-services-base-config
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/payment_db
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      configserver:
        condition: service_healthy
      mysql:
        condition: service_healthy

  cloudgateway:
    image: 'naveenkerla/cloudgateway'
    container_name: cloudgateway
    ports:
      - '9090:9090'
    extends:
      file: common-config.yaml
      service: business-services-base-config
    depends_on:
      configserver:
        condition: service_healthy
#      redis:
#        condition: service_healthy

#  redis:
#    image: 'redis:latest'
#    container_name: redis
#    ports:
#      - "6379:6379"
#    extends:
#      file: common-config.yaml
#      service: network-deploy-service
#    healthcheck:
#      test: [ "CMD", "redis-cli", "ping" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 10s

  mysql:
    image: 'mysql:oraclelinux9'
    container_name:  mysql
    ports:
      - "3306:3306"
    extends:
      file: common-config.yaml
      service: network-deploy-service
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ../mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pyour_password"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  mysql_data: